### ISSUE TITLE
引入   compile 'cn.lemon:RefreshRecyclerView:1.1.9'编译报错

### ISSUE THREAD

**Issue by wwwqqqrr** [llxdaxia/RecyclerView#10]
引入   compile 'cn.lemon:RefreshRecyclerView:1.1.9'编译报错，各种方法试了都不行。
错误:Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
错误:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException

**Comment by llxdaxia** [comment]
http://stackoverflow.com/questions/34352591/android-error-converting-byte-to-dex
先clean build，然后在 make project。

**Comment by wwwqqqrr** [comment]
还是不行，代码不是报的v4包冲突的错吗。你这个包里面引入v包了？

**Comment by llxdaxia** [comment]
没引入 v4 包。加下我 qq 。

**Comment by llxdaxia** [comment]
http://stackoverflow.com/questions/20989317/multiple-dex-files-define-landroid-support-v4-accessibilityservice-accessibility
