### ISSUE TITLE
图片加载位置错乱，怎么解决？

### ISSUE THREAD

**Issue by yaogithud** [llxdaxia/RecyclerView#11]
给imageView设置占位符、settag的方式好像是不行了，请问您有什么方法吗？

 @Override
    public void onInitializeView() {
        super.onInitializeView();
        //初始化View
        mNewImg = findViewById(R.id.news_img);
//        mNewImg.setImageDrawable(mContext.getDrawable());
//        mNewImg.setTag(mUrl);
        mNewsTitle = findViewById(R.id.news_title);
        mNewsDesc = findViewById(R.id.news_desc);
        mNewsTime = findViewById(R.id.news_time);
    }

    @Override
    public void setData(NewsBean data) {
        super.setData(data);
        //Ui绑定数据
        mUrl = data.getPicUrl();
        String realUrl = mUrl.replace("_ss", "");
//        if (mUrl.equals(mNewImg.getTag())){
        Glide.with(mContext).load(realUrl).into(mNewImg);
//        }
        mNewsTitle.setText(data.getTitle());
        mNewsDesc.setText(data.getDescription());
        mNewsTime.setText(data.getCtime());

**Comment by llxdaxia** [comment]
我测试是可以的，能贴出全部代码吗

**Comment by yaogithud** [comment]
方便加你QQ吗？

这是我的holder和adapter的代码：
public class NewsHolder extends BaseViewHolder<NewsBean> {
    private Context mContext;
    private ImageView mNewImg;
    private TextView mNewsTitle;
    private TextView mNewsDesc;
    private TextView mNewsTime;
    private String mUrl;

    public NewsHolder(View itemView) {
        super(itemView);
    }

    public void setContext(Context context) {
        this.mContext = context;
    }

    public NewsHolder(ViewGroup parent, int layoutId) {
        super(parent, layoutId);
    }

    @Override
    public void onInitializeView() {
        super.onInitializeView();
        //初始化View
        mNewImg = findViewById(R.id.news_img);
//        mNewImg.setImageDrawable(mContext.getDrawable());
//        mNewImg.setTag(mUrl);
        mNewsTitle = findViewById(R.id.news_title);
        mNewsDesc = findViewById(R.id.news_desc);
        mNewsTime = findViewById(R.id.news_time);
    }


    @Override
    public void setData(NewsBean data) {
        super.setData(data);
        //Ui绑定数据
        mUrl = data.getPicUrl();
        String realUrl = mUrl.replace("_ss", "");
//        if (mUrl.equals(mNewImg.getTag())){
        Glide.with(mContext).load(realUrl).into(mNewImg);
//        }
        mNewsTitle.setText(data.getTitle());
        mNewsDesc.setText(data.getDescription());
        mNewsTime.setText(data.getCtime());
    }

    @Override
    public void onItemViewClick(NewsBean data) {
        super.onItemViewClick(data);
        //点击事件
        Log.i("yao","onItemViewClick"+data.getUrl());
        Intent intent = new Intent(mContext, NewsDetailActivity.class);
        intent.putExtra("DATA",data.getUrl());
        mContext.startActivity(intent);
    }
}



public class NewsAdapter extends RecyclerAdapter<NewsBean> {

    private Context mContext;
    public NewsAdapter(Context context) {
        super(context);
        this.mContext = context;
    }

    @Override
    public BaseViewHolder<NewsBean> onCreateBaseViewHolder(ViewGroup parent, int viewType) {
//        View itemView = LayoutInflater.from(mContext).inflate(R.layout.item_news, parent, false);
        NewsHolder newsHolder = new NewsHolder(parent,R.layout.item_news);
        newsHolder.setContext(mContext);
        return newsHolder;
    }
}

**Comment by yaogithud** [comment]
`public class NewsAdapter extends RecyclerAdapter<NewsBean> {

    private Context mContext;
    public NewsAdapter(Context context) {
        super(context);
        this.mContext = context;
    }

    @Override
    public BaseViewHolder<NewsBean> onCreateBaseViewHolder(ViewGroup parent, int viewType) {
//        View itemView = LayoutInflater.from(mContext).inflate(R.layout.item_news, parent, false);
        NewsHolder newsHolder = new NewsHolder(parent,R.layout.item_news);
        newsHolder.setContext(mContext);
        return newsHolder;
    }
}`

**Comment by llxdaxia** [comment]
我的主页有我的QQ号。
