### ISSUE TITLE
对于GridLayoutManager，不适用？

### ISSUE THREAD

**Issue by xpfasd** [llxdaxia/RecyclerView#12]
GridLayoutManager，添加头部，已经加载更多，变成了九宫格中的第一项和最后一项

**Comment by llxdaxia** [comment]
header 和 footer 本质上就是一个 item（viewholder），你要实现header和footer横跨 3 个item 这里确实不适用，我后面解决这个问题。

**Comment by llxdaxia** [comment]
已解决你的问题。请依赖1.2.0版本。 compile 'cn.lemon:RefreshRecyclerView:1.2.0'
