### ISSUE TITLE
使用ButterKnife没反应

### ISSUE THREAD

**Issue by zhanfangzxc** [llxdaxia/RecyclerView#13]
当我把onInitializeView这个方法去掉，然后直接在BaseViewHolder的构造函数中加了一句
![image](https://user-images.githubusercontent.com/6426836/30792141-b13fa94e-a17d-11e7-9bcc-899144dc125e.png)
请问为什么setdata之后，所有的控件都没有被设置上数据

**Comment by llxdaxia** [comment]
能贴下完整代码吗。

**Comment by zhanfangzxc** [comment]
![image](https://user-images.githubusercontent.com/6426836/30793371-13b8151c-a187-11e7-9116-5b6de48aaa65.png)
![image](https://user-images.githubusercontent.com/6426836/30793382-2c05fc06-a187-11e7-8435-81e0079843ea.png)

**Comment by llxdaxia** [comment]
adapter呢，断点能打到setdata么

**Comment by zhanfangzxc** [comment]
![image](https://user-images.githubusercontent.com/6426836/30793490-e67b365a-a187-11e7-80a4-10f354999d12.png)
断点是可以走到的，但是设置上之后，界面上没有任何改变，图片都没有加载出来

**Comment by zhanfangzxc** [comment]
@llxdaxia 可以了，我把
![image](https://user-images.githubusercontent.com/6426836/30793869-61e336ce-a18a-11e7-8bbc-8e27e0f29e57.png)
中的第二行da代码去掉了，就好了

**Comment by llxdaxia** [comment]
近期会对 adapter 进行比较大的升级
