### ISSUE TITLE
remove error

### ISSUE THREAD

**Issue by gumiTeam** [llxdaxia/RecyclerView#2]
when it includes header and remove item,report                                                                        java.lang.IllegalArgumentException: Called attach on a child which is not detached: ViewHolder{3dfd2352 position=0 id=-1, oldPos=-1, pLpos:-1 no parent}

**Comment by llxdaxia** [comment]
Sorry, some time ago did not pay attention github。RecyclerView API : public void remove(int position);   bug has fixed.
