### ISSUE TITLE
Missing local.properties

### ISSUE THREAD

**Issue by luispereira** [llxdaxia/RecyclerView#3]
I'm using windows OS, and when I try to run the following: 

```
gradlew clean
```

the following happens:

```
* Where:
Script 'https://raw.githubusercontent.com/llxdaxia/GradleScript/master/bintray_v1.gradle' line: 35

* What went wrong:
A problem occurred evaluating script.
... \llxdaxia\RecyclerView\local.properties (The system cannot find the file specified)
```

I think you should either remove the bintray_v1.gradle or add the file local.properties that the bintray_v1.gradle is expecting 

I belive it has something related with this line on your bintray_v1.gradle
```
properties.load(project.rootProject.file('local.properties').newDataInputStream())
```

**Comment by llxdaxia** [comment]
remove  the line "https://raw.githubusercontent.com/llxdaxia/GradleScript/master/bintray_v1.gradle",then have a try
