### ISSUE TITLE
在xml布局中设置高度为wrap_content无效

### ISSUE THREAD

**Issue by tadeshdu** [llxdaxia/RecyclerView#4]

**Comment by llxdaxia** [comment]
你指的是RefreshRecyclerView吗？RecyclerView是没有高度的哟

**Comment by tadeshdu** [comment]
是这样的，我在一个LinearLayout里面用了多个RefreshRecyclerView 每个RefreshRecyclerView大概显示两行数据，但是不用wrap_content的话 每次都只显示第一个RefreshRecyclerView 后来我换回官方的RecyclerView就能正常显示所有内容了

**Comment by llxdaxia** [comment]
RefreshRecyclerView不仅仅是一个RecyclerView，你是要实现一个列表里面加载不同的数据结构显示不同的item样式吗？如果这样的话建议使用MultiTypeAdapter实现，效率更高哟。建议不要一个activity中加载多个RecyclerView
