### ISSUE TITLE
为什么我的加载更多不行呢

### ISSUE THREAD

**Issue by adoukei** [llxdaxia/RecyclerView#6]
mRecyclerView.setLoadMoreAction(new Action)里面的回调并不执行？

**Comment by llxdaxia** [comment]
麻烦给下详细代码和日志

**Comment by llxdaxia** [comment]
麻烦给下详细的代码和日志

**Comment by adoukei** [comment]
我用的mAdapter.setLoadMoreAction()实现的加载更多。不是demo里面的mRecyclerView。

**Comment by adoukei** [comment]
另外这个复杂数据类型还不是特别能看懂。我得继续努力

**Comment by llxdaxia** [comment]
嗯，如果有疑问，欢迎交流，qq联系
