### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by PossibleZero** [llxdaxia/RecyclerView#7]
写的不错，比较容易理解，提个小小的BUG，一直点击移除的按钮，当数据全部清除完，数据还没有加载上去的时候，会有产生数组越界的问题。

**Comment by llxdaxia** [comment]
收到，抱歉这么晚才看到，一直没收到相关邮件。

**Comment by llxdaxia** [comment]
欢迎使用 1.1.9 版本，修复了你提的 bug，欢迎指出新的 bug
